### ISSUE TITLE
Mark-Pre-All bug

### ISSUE THREAD

**Issue by ngeeyonglim** [AY2324S1-CS2103T-T11-1/tp#127]
![Screenshot 2023-11-01 at 10 24 29 PM](https://github.com/AY2324S1-CS2103T-T11-1/tp/assets/61932308/54f31a62-6442-4d6e-a243-7e3b1e924069)

**Comment by Cikguseven** [comment]
I believe this issue occurred when implementing undo/redo. I will fix this in v1.4
