### ISSUE TITLE
[PE-D][Tester C] Grade command: error message

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T11-1/tp#172]
Small grammatical error in error message.
"... should (be?) ..."
![image.png](https://raw.githubusercontent.com/junhonglow/ped/main/files/c2ea45d7-b9d3-4234-87bb-de012585ab69.png)

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: junhonglow/ped#2

**Comment by Cikguseven** [comment]
Issue is still present

**Comment by LWZ19** [comment]
I fixed it in #192, but somehow it got deleted.
