### ISSUE TITLE
[PE-D][Tester E] Unable to add student with name that only partially matches existing students

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T11-1/tp#182]
![image.png](https://raw.githubusercontent.com/victorpengmx/ped/main/files/6a794e7d-c221-4989-891c-17df7fa01811.png)

This error prevents students with parts of their names that overlap with existing students from being added, like students with the same surname.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: victorpengmx/ped#9

**Comment by LWZ19** [comment]
We cannot replicate this issue with our latest release, we only check for duplication of student numbers and posts not restrictions on other fields.
